pipeline {

  environment {
    registry = "nagypeti/jspipewithrds"
    registryCredential = '6dee8287-c5d1-4aa7-adaa-71fe835d7fbf'
    dockerImage = ''
  }

  agent any

  stages {
    stage('gradle build '){
      steps {
        sh './gradlew bootJar'
      }
    }
    stage('Build Image') {
      steps{
        script {
          dockerImage = docker.build registry + ":$BUILD_NUMBER"
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            dockerImage.push('latest')
          }
        }
      }
    }
    stage('Remove image') {
      steps{
        sh "docker rmi $registry:$BUILD_NUMBER"
      }
    }
    stage('Deploy'){
      steps {
        withAWS(credentials:'04dc3c33-f243-4662-a597-20f7e2ddd77b', region: 'eu-north-1') {
          sh "sh awsdeploy.sh ${env.BUILD_ID}"
        }
      }
    }
  }
  post {
    always {
      cleanWs()
    }
    failure {
      slackSend (
          channel: '#rueppellii-jenkins',
          color: 'danger',
          message: "${currentBuild.fullDisplayName} has failed. (<${env.BUILD_URL}|Open>)"
      )
    }
  }
}
